# Generated by Django 3.1.6 on 2021-02-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade_information',
        ),
    ]
